### ISSUE TITLE
[QUESTION] Factionwide runtime data

### ISSUE THREAD

**Issue by AmazingDreams** [PipeRift/FactionsExtension#6]
Hello. Sorry I did not know how else to ask this question. Google didn't turn up much.

How could I go about creating shared faction mutable data. For instance I want to keep track of a list of tasks for a faction. All members of this faction should be able to read and write to this list.

I have tried to extend `FFactionInfoAsset` in blueprint & C++ however this appears to be more of a way to store constant data and it is persisted.

**Comment by muit** [comment]
Since **1.8** you have the ability to customize Faction Infos with [UFactionInfoAsset](https://github.com/PipeRift/FactionsExtension/blob/master/Source/Factions/Public/Database/FactionInfoAsset.h).
This is designed so that you can **create your own InfoAsset class** (in C++ or Blueprints) and then **create assets from it**. The class is a normal C++ or BP class child of UFactionInfoAsset, and the asset can be created by adding a ***Factions/Faction Info*** and picking your class from the list.
Then you just assign the final asset of this class into your faction's info.

**Why use a class and assets of this class?**
This allows you to have many possible instances of the same class. It allows you to use the minimum classes needed when you have many factions.
